import {useEffect, useState} from 'react';
async function call(path:string, body?:unknown) {
 const r=await fetch('/api'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Friday-Request':'1'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'Check your entries.');return d;
}
export function AccessGate({onLogin}:{onLogin:()=>void}) {
 const [token]=useState(()=>new URLSearchParams(location.hash.slice(1)).get('invite')||'');
 const [mode,setMode]=useState(token?'invite':'login');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{if(token)history.replaceState(null,'',location.pathname+location.search);},[token]);
 return <div className="access-gate"><div className="gate-identity"><p className="eyebrow">PRIVATE INTELLIGENCE SYSTEM / F-01</p><div className="gate-reactor" aria-hidden="true">F</div><h1>FRIDAY</h1><p>One command center.<br/>Access by invitation.</p></div><section className="gate-form"><p className="eyebrow">IDENTITY CHECKPOINT</p><h2>{mode==='request'?'Request clearance':mode==='invite'?'Activate your access':'Welcome back'}</h2><p className="muted">{mode==='request'?'Leave your email for the owner to review.':mode==='invite'?'Use the invited email and choose your own password.':'Owner and approved team members only.'}</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try {if(mode==='request'){const d=await call('/access/request',{email});setMessage(d.message);}else{await call(mode==='invite'?'/access/accept':'/auth/login',{email,password,...(mode==='invite'?{token}:{})});onLogin();}}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}><label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label>{mode!=='request'&&<label>Password<input type="password" autoComplete={mode==='invite'?'new-password':'current-password'} minLength={12} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button className="primary full" disabled={busy}>{busy?'Processing…':mode==='request'?'Submit access request':mode==='invite'?'Activate access':'Enter command center'}</button></form><p role="status">{message}</p>{mode!=='invite'&&<button className="text-button" onClick={()=>{setMode(mode==='login'?'request':'login');setMessage('');}}>{mode==='login'?'Need access? Request approval':'Already approved? Sign in'}</button>}<p className="small muted">Owner sessions stay signed in for up to 90 days on this browser. Signing out or clearing cookies requires signing in again.</p></section></div>;
}
type Entry={id:string;email:string;status:string;created:number};
export function AccessControl(){
 const [rows,setRows]=useState<Entry[]>([]);const [message,setMessage]=useState('');const [invite,setInvite]=useState('');const [busy,setBusy]=useState(false);
 async function refresh(){setRows(await call('/access'));}
 useEffect(()=>{void call('/access').then(setRows).catch(e=>setMessage(e.message));},[]);
 return <article className="settings-card"><p className="eyebrow">OWNER CONTROL</p><h2>Access requests</h2><p className="muted">Review each email. Approve to create a single-use link, valid for 48 hours, then send it yourself. Requests are self-reported emails; confirm the person before sharing access.</p><button onClick={()=>void refresh().catch(e=>setMessage(e.message))}>Refresh requests</button><p role="status">{message}</p>{invite&&<div className="notice"><label>Invitation to send privately<input readOnly value={invite} onFocus={e=>e.target.select()}/></label><button onClick={()=>void navigator.clipboard.writeText(invite).then(()=>setMessage('Invitation copied.')).catch(()=>setMessage('Select and copy the link manually.'))}>Copy invitation</button><p>No email has been sent automatically.</p></div>}{!rows.length&&<p>No access requests yet.</p>}{rows.map(r=><div className="access-row" key={r.id}><div><strong>{r.email}</strong><p className="small">{r.status} · {new Date(r.created*1000).toLocaleString()}</p></div><div>{(r.status==='accepted'?['revoke']:['approve','deny']).map(action=><button key={action} disabled={busy} onClick={async()=>{setBusy(true);setMessage('');setInvite('');try{const d=await call('/access/'+r.id+'/review',{action});if(d.invitation)setInvite(d.invitation);await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>{action==='approve'?'Approve / issue link':action==='revoke'?'Revoke access':'Deny'}</button>)}</div></div>)}</article>;
}
