import {CinematicMedia} from './CinematicMedia';
import './command.css';

const cinematicSources = {
 hero: new URL('./assets/friday-hero.mp4', import.meta.url).href,
 assembly: new URL('./assets/friday-assembly.mp4', import.meta.url).href,
 voice: new URL('./assets/friday-voice-core.mp4', import.meta.url).href,
};
type Project={id:string;goal:string;status:string};
type Props={onChat:()=>void;onResearch:()=>void;onSettings:()=>void;onProject:(id:string)=>void;projects:Project[];conversations:number;configured:boolean;motion:boolean};
export function Cinematic({onChat,onResearch,onSettings,onProject,projects,conversations,configured,motion}:Props){
 const active=projects.filter(p=>!['succeeded','failed','cancelled'].includes(p.status)).length;
 return <section className={'command-deck '+(!motion?'still':'')}><div className="deck-top"><span>F.R.I.D.A.Y. / PRIVATE OPERATIONS</span><span>AUTHENTICATED SESSION</span></div><div className="deck-title"><p className="eyebrow">YOUR SYSTEM. YOUR COMMAND.</p><h1>At your service.</h1><p className="muted">Your intelligence workspace is standing by.</p></div><CinematicMedia sources={cinematicSources} motion={motion}/><div className="hud-grid"><aside className="hud-panel"><p className="eyebrow">WORKSPACE TELEMETRY</p><div className="hud-stat"><b>{conversations.toString().padStart(2,'0')}</b><span>Saved conversations</span></div><div className="hud-stat"><b>{projects.length.toString().padStart(2,'0')}</b><span>Research operations</span></div><div className="hud-stat"><b>{active.toString().padStart(2,'0')}</b><span>Active operations</span></div><small>Live workspace counts</small></aside><div className="reactor-area"><div className="reactor-ring outer"/><div className="reactor-ring inner"/><div className="reactor-ring track"/><div className="reactor-center"><span>FRIDAY</span><small>{configured?'MODEL CONFIGURED':'AWAITING MODEL LINK'}</small></div><span className="reactor-caption">PERSONAL INTELLIGENCE CORE</span></div><aside className="hud-panel"><p className="eyebrow">SYSTEM READINESS</p><div className="system-line"><i/>Persistent storage<span>READY</span></div><div className="system-line"><i/>Model connection<span>{configured?'CONFIGURED':'SETUP'}</span></div><p className="small muted">Voice, computer control, and device connections remain planned.</p><button onClick={onSettings}>System controls ↗</button></aside></div><div className="command-actions"><button onClick={onChat}><small>01 / COMMUNICATION</small><strong>Open conversation ↗</strong><span>Resume thinking with FRIDAY</span></button><button onClick={onResearch}><small>02 / INVESTIGATION</small><strong>Launch research ↗</strong><span>Evidence, activity, saved reports</span></button><button onClick={onSettings}><small>03 / CONTROL</small><strong>Access & settings ↗</strong><span>Identity, approvals, services</span></button></div>{projects.length>0&&<div className="hud-panel"><p className="eyebrow">RECENT OPERATIONS</p>{projects.slice(0,3).map(p=><button className="operation" onClick={()=>onProject(p.id)} key={p.id}><span>{p.goal}</span><small>{p.status} ↗</small></button>)}</div>}<footer className="deck-footer">PRIVATE WORKSPACE <span>OWNER-CONTROLLED ACCESS · NO PUBLIC SIGNUP</span></footer></section>;
}
